### ISSUE TITLE
weights and biases

### ISSUE THREAD

**Issue by APJansen** [UNSAT3D/.github#4]
Could you go to https://wandb.ai/home, link it to your github account and create an academic team called UNSAT3D?
The button should be on the very bottom left.
I just tried to do it, but apparently you can only have one academic team. I can create a "work" team, but that probably has disadvantages. I hope that if you create it I'll be able to join it.

This is a site for tracking ML training runs.

**Comment by PabRod** [comment]
I just created [it](https://wandb.ai/unsat3d) and invited @APJansen via his institutional e-mail address.

**Comment by APJansen** [comment]
Thanks! I received the invite, but I only see that it's a private team when I click it, probably because I already have a team. I'll wait until after the weekend in case it's just a delay, otherwise it's not much of a problem to leave the other team I think.

**Comment by APJansen** [comment]
@PabRod I have left the other team but am still not able to join. Could you try uninviting me if necessary and reinviting? Sorry for the hassle..

**Comment by PabRod** [comment]
Done! Hope it helps.

**Comment by PabRod** [comment]
Fixed by using same email account as the one used for github.
